from __future__ import annotations

from typing import Any, Sequence

import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.multioutput import MultiOutputClassifier


class SubtopicRF:
    """Multilabel Random Forest classifier for subtopic prediction."""

    def __init__(
        self,
        n_estimators: int = 200,
        max_depth: int | None = None,
        min_samples_split: int = 2,
        min_samples_leaf: int = 1,
        random_state: int = 42,
        n_jobs: int = -1,
    ) -> None:
        self.model = MultiOutputClassifier(
            estimator=RandomForestClassifier(
                n_estimators=n_estimators,
                max_depth=max_depth,
                min_samples_split=min_samples_split,
                min_samples_leaf=min_samples_leaf,
                random_state=random_state,
                n_jobs=1,
            ),
            n_jobs=n_jobs,
        )
        self.labels_: np.ndarray | None = None
        self.classes_: list[np.ndarray] | None = None

    def fit(self, X: Any, y: Any, labels: Sequence[str] | None = None) -> "SubtopicRF":
        """
        Train the multilabel subtopic classifier.

        Parameters
        ----------
        X : array-like of shape (n_samples, n_features)
            Training features.
        y : array-like of shape (n_samples, n_labels) or (n_samples,)
            Binary label matrix or single-label targets.
        labels : sequence of str, optional
            Names for each output label column. When omitted, integer labels are used.
        """
        y_array = np.asarray(y)
        if y_array.ndim == 1:
            y_array = y_array.reshape(-1, 1)
        if y_array.ndim != 2:
            raise ValueError("y must be a 1D or 2D array-like structure.")

        if labels is None:
            labels = [str(i) for i in range(y_array.shape[1])]
        if len(labels) != y_array.shape[1]:
            raise ValueError(
                "The number of provided labels must match the number of target columns."
            )

        self.labels_ = np.asarray(labels)
        self.model.fit(X, y_array.astype(int))
        self.classes_ = [estimator.classes_ for estimator in self.model.estimators_]
        return self

    def predict(self, X: Any) -> np.ndarray:
        """Predict the multilabel binary indicator matrix."""
        if self.labels_ is None:
            raise RuntimeError("Model must be fitted before prediction.")
        return self.model.predict(X).astype(int)

    def predict_proba(self, X: Any) -> np.ndarray:
        """Return the positive-class probability for each subtopic label."""
        if self.labels_ is None:
            raise RuntimeError("Model must be fitted before prediction.")

        probabilities = [
            estimator.predict_proba(X)[:, 1] for estimator in self.model.estimators_
        ]
        return np.column_stack(probabilities)

    def transform(self, X: Any) -> dict[str, Any]:
        """Generate subtopic features for downstream models."""
        predictions = self.predict(X)
        probabilities = self.predict_proba(X)
        return {
            "subtopic": predictions,
            "subtopic_proba": probabilities,
            "subtopic_labels": self.labels_,
        }

    def get_feature_names(self) -> list[str]:
        """Return names of the probability features generated by this classifier."""
        if self.labels_ is None:
            raise RuntimeError("Model must be fitted first.")

        return [f"subtopic_{str(label)}_proba" for label in self.labels_]

    def get_params(self) -> dict[str, Any]:
        """Return model parameters."""
        return self.model.get_params()
